plot:
  theme:
    - custom
    - ggplot default
    - ggplot dark
    - ggplot light
    - ggplot bw
  grouping:
    - organism

data:
  genomes:
    Bacillus subtilis 168:
      - 224308
    Cupriavidus necator H16:
      - 381666
    Escherichia coli BL21:
      - 469008
    Pseudomonas aeruginosa PAO1:
      - 208964
    Pseudomonas putida KT2440:
      - 160488
    Streptococcus pneumoniae R6:
      - 171101
    Streptococcus pyogenes serotype M1 GAS:
      - 301447
    Streptomyces coelicolor ATCC BAA-471:
      - 100226
    Salmonella typhimurium LT2:
      - 99287
